# Data Structures: Numpy Array

Any number of dimensions, each element with the same type.

In [1]:
import numpy as np

### 1.1. Create Arrays

In [2]:
print(np.array([[1, 2, 3, 4], [5, 6, 7, 8]]))

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
print(np.array([1, 2, 3, 4, 5, 6, 7, 8]).reshape(2, 4))

[[1 2 3 4]
 [5 6 7 8]]


### 1.2. Create Arrays of Specific Values

In [4]:
print(np.zeros((2, 4)))

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [5]:
print(np.ones((2, 4)))

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [6]:
print(np.full((2, 4), 1.0))

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [7]:
print(np.random.random((2, 4)))

[[ 0.96608523  0.03263587  0.92793829  0.92080139]
 [ 0.73297414  0.02404695  0.55897552  0.05515607]]


In [8]:
print(np.eye(4))

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


### 1.3. Create Arrays of Evenly Spaced Values

In [9]:
print(np.arange(1.0, 9.0, 1.0).reshape(2, 4))

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]]


In [10]:
print(np.linspace(1.0, 8.0, 8).reshape(2, 4))

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]]


### 2.1. Size of Arrays

In [11]:
a1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]); print(a1)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
print(a1.ndim)

2


In [13]:
print(a1.size)

8


In [14]:
print(a1.shape)

(2, 4)


### 2.2. Data Type of Arrays

In [15]:
print(np.array([[1, 2, 3, 4], [5, 6, 7, 8]]).dtype)

int32


In [16]:
print(np.array([[1, 2, 3, 4], [5, 6, 7, 8]]).astype(str))

[['1' '2' '3' '4']
 ['5' '6' '7' '8']]


### 3.1. Rotate Arrays

In [17]:
a2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]); print(a2)

[[1 2 3 4]
 [5 6 7 8]]


In [18]:
print(np.flipud(a2))

[[5 6 7 8]
 [1 2 3 4]]


In [19]:
print(np.fliplr(a2))

[[4 3 2 1]
 [8 7 6 5]]


In [20]:
print(a2.T)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [21]:
print(np.rot90(a2, k=1))

[[4 8]
 [3 7]
 [2 6]
 [1 5]]


In [22]:
print(np.roll(a2, shift=1))

[[8 1 2 3]
 [4 5 6 7]]


### 3.2. Combine and Split Arrays

In [23]:
a3 = np.array([[1, 2], [3, 4]]); print(a3)
a4 = np.array([[5, 6], [7, 8]]); print(a4)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [24]:
print(np.vstack((a3, a4)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [25]:
print(np.hstack((a3, a4)))

[[1 2 5 6]
 [3 4 7 8]]


In [26]:
a5 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]); print(a5)

[[1 2 3 4]
 [5 6 7 8]]


In [27]:
print(np.vsplit(a5, 2)[0])
print(np.vsplit(a5, 2)[1])

[[1 2 3 4]]
[[5 6 7 8]]


In [28]:
print(np.hsplit(a5, 2)[0])
print(np.hsplit(a5, 2)[1])

[[1 2]
 [5 6]]
[[3 4]
 [7 8]]


### 4.1. Arithmetic Operations of Arrays

In [29]:
print(np.array([[10, 20], [30, 40]]) + 10)

[[20 30]
 [40 50]]


In [30]:
print(np.array([[10, 20], [30, 40]]) - 10)

[[ 0 10]
 [20 30]]


In [31]:
print(np.array([[10, 20], [30, 40]]) * 2)

[[20 40]
 [60 80]]


In [32]:
print(np.array([[10, 20], [30, 40]]) / 2)

[[  5.  10.]
 [ 15.  20.]]


In [33]:
print(np.array([[10, 20], [30, 40]]) % 2)

[[0 0]
 [0 0]]


In [34]:
print(np.array([[10, 20], [30, 40]]) ** 2)

[[ 100  400]
 [ 900 1600]]


In [35]:
print(np.exp(np.array([[1, 0], [0, 1]])))

[[ 2.71828183  1.        ]
 [ 1.          2.71828183]]


In [36]:
print(np.log(np.array([[2.71828183, 1], [1, 2.71828183]])))

[[ 1.  0.]
 [ 0.  1.]]


In [37]:
print(np.sqrt(np.array([[100, 1], [1, 100]])))

[[ 10.   1.]
 [  1.  10.]]


In [38]:
print(np.round(np.sin(np.array([[(1/2)*np.pi, 1*np.pi], [(3/2)*np.pi, 2*np.pi]])), 3))

[[ 1.  0.]
 [-1. -0.]]


In [39]:
print(np.round(np.cos(np.array([[(1/2)*np.pi, 1*np.pi], [(3/2)*np.pi, 2*np.pi]])), 3))

[[ 0. -1.]
 [-0.  1.]]


In [40]:
print(np.round(np.tan(np.array([[0*np.pi, (1/4)*np.pi], [(3/4)*np.pi, 1*np.pi]])), 3))

[[ 0.  1.]
 [-1. -0.]]


In [41]:
a6 = np.array([[1, 3], [6, 9]]); print(a6)
a7 = np.array([[1, 2], [2, 1]]); print(a7)

[[1 3]
 [6 9]]
[[1 2]
 [2 1]]


In [42]:
print(a6 + a7)

[[ 2  5]
 [ 8 10]]


In [43]:
print(a6 - a7)

[[0 1]
 [4 8]]


In [44]:
print(a6 * a7)

[[ 1  6]
 [12  9]]


In [45]:
print(a6 / a7)

[[ 1.   1.5]
 [ 3.   9. ]]


In [46]:
print(a6 % a7)

[[0 1]
 [0 0]]


In [47]:
print(a6 ** a7)

[[ 1  9]
 [36  9]]


In [48]:
print(np.dot(a6, a7))

[[ 7  5]
 [24 21]]


### 4.2. Aggregate Functions of Arrays

In [49]:
a8 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]); print(a8)

[[1 2 3 4]
 [5 6 7 8]]


In [50]:
print(np.sum(a8, axis=0))
print(np.sum(a8, axis=1))

[ 6  8 10 12]
[10 26]


In [51]:
print(np.cumsum(a8, axis=0))
print(np.cumsum(a8, axis=1))

[[ 1  2  3  4]
 [ 6  8 10 12]]
[[ 1  3  6 10]
 [ 5 11 18 26]]


In [52]:
print(np.mean(a8, axis=0))
print(np.mean(a8, axis=1))

[ 3.  4.  5.  6.]
[ 2.5  6.5]


In [53]:
print(np.std(a8, axis=0))
print(np.std(a8, axis=1))

[ 2.  2.  2.  2.]
[ 1.11803399  1.11803399]


In [54]:
print(np.min(a8, axis=0))
print(np.min(a8, axis=1))

[1 2 3 4]
[1 5]


In [55]:
print(np.max(a8, axis=0))
print(np.max(a8, axis=1))

[5 6 7 8]
[4 8]


In [56]:
print(np.median(a8, axis=0))
print(np.median(a8, axis=1))

[ 3.  4.  5.  6.]
[ 2.5  6.5]
