# DP: Floyd-Warshall Algorithm

For all pairs shortest paths problem. Floyd-Warshall algorithm finds the shortest paths between all pairs of vertices in a weighted graph with positive or negative edge weights (but with no negative cycles).

In [1]:
import numpy as np

### Initialize

'n' is the total number of vertices and 'D' is an array representing the edge weights. Because the objective of this algorithm is to find the shortest paths, the value in D is set to infinite if the two vertices are not connected.

In [2]:
n = 4

In [3]:
v0 = [0, 8, float("inf"), 1]
v1 = [float("inf"), 0, 1, float("inf")]
v2 = [4, float("inf"), 0, float("inf")]
v3 = [float("inf"), 2, 9, 0]

In [4]:
D = np.array(v0 + v1 + v2 + v3).reshape(n, n)
print(D)

[[  0.   8.  inf   1.]
 [ inf   0.   1.  inf]
 [  4.  inf   0.  inf]
 [ inf   2.   9.   0.]]


In [5]:
V = np.full((n, n), "#")
print(V)

[['#' '#' '#' '#']
 ['#' '#' '#' '#']
 ['#' '#' '#' '#']
 ['#' '#' '#' '#']]


### Execute

'k' means the intermediate vertex. On each step, the algorithm compares weights from the direct path and the path via k. If the latter has a lower value, D is updated and k is recorded on array V. For instance, when k is 0, since 2-0-1(weight=12) has a lower value than 2-1(weight=infinite), the value of V[2][1] becomes 0.

In [6]:
k = 0

In [7]:
for i in range(0, n):
    if i != k:
        for j in range(0, n):
            if j != k and j != i:
                if (D[i][k] + D[k][j]) < D[i][j]:
                    print("{}-{}({})".format(i, j, D[i][j]))
                    print("{}-{}-{}({})".format(i, k, j, (D[i][k] + D[k][j])))
                    D[i][j] = D[i][k] + D[k][j]
                    V[i][j] = k

2-1(inf)
2-0-1(12.0)
2-3(inf)
2-0-3(5.0)


In [8]:
print(D)

[[  0.   8.  inf   1.]
 [ inf   0.   1.  inf]
 [  4.  12.   0.   5.]
 [ inf   2.   9.   0.]]


In [9]:
print(V)

[['#' '#' '#' '#']
 ['#' '#' '#' '#']
 ['#' '0' '#' '0']
 ['#' '#' '#' '#']]


In [10]:
k = 1

In [11]:
for i in range(0, n):
    if i != k:
        for j in range(0, n):
            if j != k and j != i:
                if (D[i][k] + D[k][j]) < D[i][j]:
                    print("{}-{}({})".format(i, j, D[i][j]))
                    print("{}-{}-{}({})".format(i, k, j, (D[i][k] + D[k][j])))
                    D[i][j] = D[i][k] + D[k][j]
                    V[i][j] = k

0-2(inf)
0-1-2(9.0)
3-2(9.0)
3-1-2(3.0)


In [12]:
print(D)

[[  0.   8.   9.   1.]
 [ inf   0.   1.  inf]
 [  4.  12.   0.   5.]
 [ inf   2.   3.   0.]]


In [13]:
print(V)

[['#' '#' '1' '#']
 ['#' '#' '#' '#']
 ['#' '0' '#' '0']
 ['#' '#' '1' '#']]


In [14]:
k = 2

In [15]:
for i in range(0, n):
    if i != k:
        for j in range(0, n):
            if j != k and j != i:
                if (D[i][k] + D[k][j]) < D[i][j]:
                    print("{}-{}({})".format(i, j, D[i][j]))
                    print("{}-{}-{}({})".format(i, k, j, (D[i][k] + D[k][j])))
                    D[i][j] = D[i][k] + D[k][j]
                    V[i][j] = k

1-0(inf)
1-2-0(5.0)
1-3(inf)
1-2-3(6.0)
3-0(inf)
3-2-0(7.0)


In [16]:
print(D)

[[  0.   8.   9.   1.]
 [  5.   0.   1.   6.]
 [  4.  12.   0.   5.]
 [  7.   2.   3.   0.]]


In [17]:
print(V)

[['#' '#' '1' '#']
 ['2' '#' '#' '2']
 ['#' '0' '#' '0']
 ['2' '#' '1' '#']]


In [18]:
k = 3

In [19]:
for i in range(0, n):
    if i != k:
        for j in range(0, n):
            if j != k and j != i:
                if (D[i][k] + D[k][j]) < D[i][j]:
                    print("{}-{}({})".format(i, j, D[i][j]))
                    print("{}-{}-{}({})".format(i, k, j, (D[i][k] + D[k][j])))
                    D[i][j] = D[i][k] + D[k][j]
                    V[i][j] = k

0-1(8.0)
0-3-1(3.0)
0-2(9.0)
0-3-2(4.0)
2-1(12.0)
2-3-1(7.0)


In [20]:
print(D)

[[ 0.  3.  4.  1.]
 [ 5.  0.  1.  6.]
 [ 4.  7.  0.  5.]
 [ 7.  2.  3.  0.]]


In [21]:
print(V)

[['#' '3' '3' '#']
 ['2' '#' '#' '2']
 ['#' '3' '#' '0']
 ['2' '#' '1' '#']]
