# DP: 0/1 Knapsack Algorithm

For combinatorial optimization problem. Knapsack algorithm determines the number of each item to include in a collection. Since a knapsack has a fixed capacity and each item has a weight as well as a value, the total weight should be less than or equal to the limit of the given knapsack, while maximizing the total value.

There are 2 types of knapsack algorithm. Here, 0/1 knapsack algorithm is mainly discussed. It restricts the number of each kind of item to one. The other is called fractional knapsack algorithm, which allows splitting an item. While fractional knapsack algorithm is a greedy algorithm, 0/1 knapsack algorithm is a dynamic programming approach.

In [1]:
import numpy as np

### Initialize

In [2]:
C = 10
X = {1:[5, 10], 2:[4, 40], 3:[6, 30], 4:[3, 50]} ## {item:[weight, value]}
n = len(X)

In [3]:
K = np.zeros((n+1, C+1))

In [4]:
print(K)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


### Execute

In [5]:
for i in range(1, n+1):
    for w in range(1, C+1):
        if X[i][0] > w:
            K[i][w] = K[i-1][w]
        else:
            K[i][w] = max(K[i-1][w], (K[i-1][w-X[i][0]] + X[i][1]))

In [6]:
print(K)

[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  10.  10.  10.  10.  10.  10.]
 [  0.   0.   0.   0.  40.  40.  40.  40.  40.  50.  50.]
 [  0.   0.   0.   0.  40.  40.  40.  40.  40.  50.  70.]
 [  0.   0.   0.  50.  50.  50.  50.  90.  90.  90.  90.]]


In [7]:
print("Value:", K[n][C])

Value: 90.0


In [8]:
l = []

In [9]:
for i in reversed(range(1, n+1)):
    if K[i][C] != K[i-1][C]:
        l.append(i)
        C = C - X[i][0]

In [10]:
print("Item:", sorted(l))

Item: [2, 4]
